Sati\ControleSatiBundle\Entity\Caixa:
    type: entity
    table: caixa
    id:
        idCaixa:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_caixa
            generator:
                strategy: IDENTITY
    fields:
        tipoMovimentacao:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: "0-entrada\n1-saida"
            column: tipo_movimentacao
        statusMoventacao:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: "0-a pgar/receber\n1- pago/recebido\n2-estornado"
            column: status_moventacao
        data:
            type: date
            nullable: false
        origem:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
